# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2af7e2066c23a3b436f048605f88de63"
name = "fetch customer data"
application_url = "https://fetch-customer-data-8rn8d.ondigitalocean.app"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers, read_metaobjects, read_metaobjects, read_metaobject_definitions"

[auth]
redirect_urls = [ "https://fetch-customer-data-8rn8d.ondigitalocean.app/api/auth" ]
